### ISSUE TITLE
base_lin_vel calculate

### ISSUE THREAD

**Issue by BruceXing24** [lupinjia/genesis_lr#3]
![issue1](https://github.com/user-attachments/assets/96218103-3bd8-442b-81bc-ad03eb8be50c)
![issue2](https://github.com/user-attachments/assets/b8b13ca3-2f2e-4751-8ac7-b1ddb1d75173)

Hi, thanks for sharing.
I found a problem about **base_lin_vel**  when i train a biped robot. In picture 2 there is function **transform_by_quat**, after this func i got some big and strange values , like from 5.9210e-02 to 37.60.

**Comment by lupinjia** [comment]
Well, according to the output, the raw base_lin_vel(in world frame) has a big value in Z direction, which may be caused by gravity. After transformation, the big value appears on X direction of base frame, so maybe because the robot is initialized face down? Just a guess
